version: '3.4'
services:
#  Optional
#  distributed-caching-community-alfresco-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: distributed-caching-community-alfresco-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
#  distributed-caching-community-alfresco-acs:
  alfresco1:
    image: alfresco-content-services-distributed-caching-community-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: >-
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url="failover:(nio://distributed-caching-community-alfresco-activemq:61616)?timeout=3000&jms.useCompression=true"
        --add-modules java.se
        --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
        --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
        --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
        --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
        --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
        --add-opens=java.base/java.nio=ALL-UNNAMED
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.io=ALL-UNNAMED
        --add-opens=java.base/java.util=ALL-UNNAMED
        --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        --add-opens=java.base/javax.crypto=ALL-UNNAMED
        --illegal-access=permit
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:+UseStringDeduplication
        -XX:+ScavengeBeforeFullGC
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -Dfile.encoding=UTF-8
        -Djava.net.preferIPv4Stack=true
        -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
        -DIGNITE_QUIET=true
        -DIGNITE_NO_ASCII=true
        -DIGNITE_UPDATE_NOTIFIER=false
        -DIGNITE_JVM_PAUSE_DETECTOR_DISABLED=true
        -DIGNITE_SKIP_CONFIGURATION_CONSISTENCY_CHECK=true
        -Daldica.caches.remoteSupport.enabled=true
        -Daldica.core.local.id=alfresco1
        -Daldica.core.public.host=alfresco1
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - distributed-caching-community-alfresco-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - distributed-caching-community-alfresco-postgres
  
  alfresco2:
    image: alfresco-content-services-distributed-caching-community-alfresco:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: >-
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url="failover:(nio://distributed-caching-community-alfresco-activemq:61616)?timeout=3000&jms.useCompression=true"
        --add-modules java.se
        --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
        --add-exports=java.base/sun.nio.ch=ALL-UNNAMED
        --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED
        --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED
        --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
        --add-opens=java.base/java.nio=ALL-UNNAMED
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.io=ALL-UNNAMED
        --add-opens=java.base/java.util=ALL-UNNAMED
        --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        --add-opens=java.base/javax.crypto=ALL-UNNAMED
        --illegal-access=permit
        -XX:+UseG1GC
        -XX:+ParallelRefProcEnabled
        -XX:+UseStringDeduplication
        -XX:+ScavengeBeforeFullGC
        -XX:+DisableExplicitGC
        -XX:+AlwaysPreTouch
        -Dfile.encoding=UTF-8
        -Djava.net.preferIPv4Stack=true
        -DIGNITE_PERFORMANCE_SUGGESTIONS_DISABLED=true
        -DIGNITE_QUIET=true
        -DIGNITE_NO_ASCII=true
        -DIGNITE_UPDATE_NOTIFIER=false
        -DIGNITE_JVM_PAUSE_DETECTOR_DISABLED=true
        -DIGNITE_SKIP_CONFIGURATION_CONSISTENCY_CHECK=true
        -Daldica.caches.remoteSupport.enabled=true
        -Daldica.core.local.id=alfresco2
        -Daldica.core.public.host=alfresco2
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "8180:8080"
    volumes:
      - distributed-caching-community-alfresco-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - distributed-caching-community-alfresco-postgres

  distributed-caching-community-alfresco-postgres:
    image: postgres:16.5
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - distributed-caching-community-alfresco-db-volume:/var/lib/postgresql/data

  distributed-caching-community-alfresco-ass:
    image: alfresco/alfresco-search-services:2.0.15
    environment:
      SOLR_ALFRESCO_HOST: alfresco1
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: distributed-caching-community-alfresco-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - distributed-caching-community-alfresco-ass-volume:/opt/alfresco-search-services/contentstore
      - distributed-caching-community-alfresco-ass-volume:/opt/alfresco-search-services/data
  distributed-caching-community-alfresco-activemq:
      image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  distributed-caching-community-alfresco-acs-volume:
    external: true
  distributed-caching-community-alfresco-db-volume:
    external: true
  distributed-caching-community-alfresco-ass-volume:
    external: true
